id: AFA4D4B55
title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of the
  Guru (Lama Sangdü)'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:48:55.502944
  last_modified_at: 2022-03-01 00:48:55.502947
