id: AFA4D4B55
title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound Guardians'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:48:55.493882
  last_modified_at: 2022-03-01 00:48:55.493910
