id: AFA4D4B55
title: The Secret Vajra Knot
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:48:55.506989
  last_modified_at: 2022-03-01 00:48:55.506992
