id: AFA4D4B55
title: General Long-Life Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:48:55.498308
  last_modified_at: 2022-03-01 00:48:55.498310
